/* This file was generated by SableCC (http://www.sablecc.org/). */

package configuration.node;

import java.util.*;
import configuration.analysis.*;

@SuppressWarnings("nls")
public final class AGrammar extends PGrammar
{
    private final LinkedList<PDef> _def_ = new LinkedList<PDef>();

    public AGrammar()
    {
        // Constructor
    }

    public AGrammar(
        @SuppressWarnings("hiding") List<?> _def_)
    {
        // Constructor
        setDef(_def_);

    }

    @Override
    public Object clone()
    {
        return new AGrammar(
            cloneList(this._def_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGrammar(this);
    }

    public LinkedList<PDef> getDef()
    {
        return this._def_;
    }

    public void setDef(List<?> list)
    {
        for(PDef e : this._def_)
        {
            e.parent(null);
        }
        this._def_.clear();

        for(Object obj_e : list)
        {
            PDef e = (PDef) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._def_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._def_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._def_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDef> i = this._def_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDef) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
