/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import java.util.*;
import expression.analysis.*;

@SuppressWarnings("nls")
public final class AGrammar extends PGrammar
{
    private final LinkedList<PExpdef> _expdef_ = new LinkedList<PExpdef>();

    public AGrammar()
    {
        // Constructor
    }

    public AGrammar(
        @SuppressWarnings("hiding") List<?> _expdef_)
    {
        // Constructor
        setExpdef(_expdef_);

    }

    @Override
    public Object clone()
    {
        return new AGrammar(
            cloneList(this._expdef_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGrammar(this);
    }

    public LinkedList<PExpdef> getExpdef()
    {
        return this._expdef_;
    }

    public void setExpdef(List<?> list)
    {
        for(PExpdef e : this._expdef_)
        {
            e.parent(null);
        }
        this._expdef_.clear();

        for(Object obj_e : list)
        {
            PExpdef e = (PExpdef) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expdef_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expdef_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expdef_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpdef> i = this._expdef_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpdef) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
